Repository ucsb-cs156-s23/proj-courses-s23-7pm-1, pull requests merged in 2023-06, with the labels that each got.

#45 CJB - Fix Subject Search Not Working on Default Value
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/BasicCourseSearch/CourseOverTimeSearchForm.js
Labels: 10

#48 rh - Add Grade History controller, GET search endpoint, service, utility, and GitHub API endpoint
  pom.xml
  src/main/java/edu/ucsb/cs156/courses/controllers/GradeHistoryController.java
  src/main/java/edu/ucsb/cs156/courses/entities/GradeHistory.java
  src/main/java/edu/ucsb/cs156/courses/models/github/ApiResult.java
  src/main/java/edu/ucsb/cs156/courses/models/github/TreeElement.java
  src/main/java/edu/ucsb/cs156/courses/repositories/GradeHistoryRepository.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBGradeHistoryService.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBGradeHistoryServiceImpl.java
  src/main/java/edu/ucsb/cs156/courses/utilities/CourseUtilities.java
  src/test/java/edu/ucsb/cs156/courses/controllers/GradeHistoryControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/entities/GradeHistoryTests.java
  src/test/java/edu/ucsb/cs156/courses/fixtures/GradeHistoryFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBGradeHistoryServiceTests.java
  src/test/java/edu/ucsb/cs156/courses/utilities/CourseUtilitiesTests.java
Labels: 10

#52 pc - update workflows 12 and 13 to publish to github pages
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff

#36 Ben instructor search page
  frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
  frontend/src/main/pages/CourseInstructor/CourseInstructorIndexPage.js
  frontend/src/stories/components/BasicCourseSearch/InstructorCourseSearchForm.stories.js
  frontend/src/stories/pages/CourseInstructorIndexPage.stories.js
  frontend/src/tests/components/BasicCourseSearch/InstructorCourseSearchForm.test.js
  frontend/src/tests/pages/CourseInstructor/CourseInstructorIndexPage.test.js
Labels: Merge Candidate

#55 Upload Grade History Data Job and Factory
  src/main/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJob.java
  src/main/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobFactory.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/courses/jobs/UploadGradeDataJobTests.java
Labels: 10

#57 BUGFIX: Images don't show up reliably on localhost
  src/main/java/edu/ucsb/cs156/courses/controllers/FrontendProxyController.java
Labels: 10

#59 REFACTOR: Replace logger with @Slf4j
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsController.java
  src/main/java/edu/ucsb/cs156/courses/documents/Course.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsControllerTests.java
Labels: 5
